include: package:lints/recommended.yaml

analyzer:
  #  strong-mode:
  #    implicit-dynamic: false
  #    implicit-casts: false

  enable-experiment:
    - non-nullable

  errors:
    unused_import: error
    dead_code: error
    prefer_final_locals: warning
    use_key_in_widget_constructors: ignore
    invalid_annotation_target: ignore
    prefer_const_constructors: ignore
    avoid_print: ignore

linter:
  rules:
    - avoid_void_async